### ISSUE TITLE
 The following services generated Max Retry Reached errors: PDFId 

### ISSUE THREAD

**Issue by james-mariano** [CybercentreCanada/assemblyline-service-pdfid#7]
I'm receiving this error when scanning a PDF through Assemblyline. Can you provide any guidance?

**Comment by cccs-rs** [comment]
Hello!

I can for sure provide guidance on this issue. Can you start with detailing what the issue is or errors if you have any on-hand.

**Comment by james-mariano** [comment]
No worries! I appreciate the prompt reply. The PDF is too large to send through e-mail so I’ve provided a Dropbox link:

[https://www.dropbox.com/s/vey0oj28t2krlje/Ebook-%20Why%20are%20Businesses%20Moving%20Custom%20Apps%20to%20the%20Cloud.pdf?dl=0](https://www.dropbox.com/s/vey0oj28t2krlje/Ebook- Why are Businesses Moving Custom Apps to the Cloud.pdf?dl=0)

Please use caution with this file as I’m not certain if it contains malicious content. I was able to determine that Javascript is embedded after running PDFId outside of Assemblyline.

I appreciate your help!

Best,
James

**Comment by james-mariano** [comment]
Interesting. Well I’m glad to hear no malicious content was identified.

I believe my organization is currently using the latest version of Assembyline—4.0.1.2. I know we’re at least on version 4 of the product.

I can see a “submissions.max.size” config parameter currently set to “1200000000” (I assume 1.2GB). Is there another variable that I should investigate?

**Comment by cccs-rs** [comment]
I would try to update to and run 4.0.1.4 since that seems to be the latest stable release for PDFId and see if that issue persists.

![image](https://user-images.githubusercontent.com/62077998/136086112-37b70a59-4b7b-4441-aa2c-eef0911c7b75.png)


The limit that I mentioned is part of the service's config, as seen below:
![image](https://user-images.githubusercontent.com/62077998/136086324-52190047-f197-4bb5-8e9f-bfd239c013dc.png)

**Comment by james-mariano** [comment]
Perfect! After further review, it turns out we may still be AL v3.3. I was under the impression that we’ve upgraded to 4 at this point. I’ll continue to troubleshoot on my end. I greatly appreciate your help with this!
